### ISSUE TITLE
Failing tests on master

### ISSUE THREAD

**Issue by christetreault** [ucsd-progsys/liquidhaskell#467]
I'm getting the following test suite failures in the current master build:

```
    eq_pos
      Append-rj.hs:                           FAIL (5.12s)
        Wrong exit code
        expected: ExitSuccess
         but got: ExitFailure 1
      Append2.hs:                             OK (4.52s)
      Append.hs:                              OK (3.47s)
    eq_neg
      Append-rj.hs:                           OK (5.07s)
      Append2.hs:                             FAIL (4.45s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
      Append.hs:                              FAIL (3.50s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
```

**Comment by christetreault** [comment]
Are these lines correct? https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/test.hs#L97-L98

**Comment by nikivazou** [comment]
I will rearrange the test. 
The lines are corrent, but why does not Travis check these tests?

**Comment by christetreault** [comment]
`testGroup "eq_neg" <$> dirTests "tests/equationalproofs/pos"` is correct? If so, this line is very confusing to me. It seems to me to be the sort of thing some maintainer 5 years from now will screw up...

**Comment by gridaphobe** [comment]
@nikivazou you need to tell travis to check them in `.travis.yml`

https://github.com/ucsd-progsys/liquidhaskell/blob/master/.travis.yml#L15-L27

Unfortunately our testsuite is too large to run in a single session.

**Comment by nikivazou** [comment]
Oh, yes, or I can just add them to Unit, right?

On Thu, Sep 24, 2015 at 11:46 AM, Eric Seidel <notifications@github.com>
wrote:

> @nikivazou <https://github.com/nikivazou> you need to tell travis to
> check them in .travis.yml
>
>
> https://github.com/ucsd-progsys/liquidhaskell/blob/master/.travis.yml#L15-L27
>
> Unfortunately our testsuite is too large to run in a single session.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/467#issuecomment-143016531>
> .
>



-- 
Niki Vazou

**Comment by nikivazou** [comment]
@christetreault is it fixed now?

**Comment by christetreault** [comment]
`eq_pos` is good. `eq_neg` is still broken:

```
$ ./dist/build/test/test -p 'eq_neg/'
Tests
  Unit
    eq_neg
      AppendVerbose.hs:  FAIL (4.64s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
      MapFusionArrow.hs: FAIL (3.57s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
      Append.hs:         FAIL (3.59s)
        Wrong exit code
        expected: ExitFailure 1
         but got: ExitSuccess
```

On my machine, changing [Line 87](https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/test.hs#L87) to `testGroup "eq_neg" <$> dirTests "tests/equationalproofs/neg` makes the test pass.

**Comment by nikivazou** [comment]
Of course you need this change... Sorry. Can you push it?

On Thu, Sep 24, 2015 at 12:12 PM, Chris Tetreault <notifications@github.com>
wrote:

> eq_pos is good. eq_neg is still broken:
>
> $ ./dist/build/test/test -p 'eq_neg/'
> Tests
>   Unit
>     eq_neg
>       AppendVerbose.hs:  FAIL (4.64s)
>         Wrong exit code
>         expected: ExitFailure 1
>          but got: ExitSuccess
>       MapFusionArrow.hs: FAIL (3.57s)
>         Wrong exit code
>         expected: ExitFailure 1
>          but got: ExitSuccess
>       Append.hs:         FAIL (3.59s)
>         Wrong exit code
>         expected: ExitFailure 1
>          but got: ExitSuccess
>
> On my machine, changing Line 87
> <https://github.com/ucsd-progsys/liquidhaskell/blob/master/tests/test.hs#L87>
> to testGroup "eq_neg" <$> dirTests "tests/equationalproofs/neg makes the
> test pass.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/467#issuecomment-143022563>
> .
>



-- 
Niki Vazou

**Comment by ranjitjhala** [comment]
I was fiddling around with these, didn't realize they were in the regressions!
but have removed `Append-rj.hs` and nothing in the `neg/`

**Comment by christetreault** [comment]
@nikivazou Sorry, had to go to class. I just re-tested and we're good now, thanks!
