### ISSUE TITLE
Free vars in qualifiers: Resolve.hs

### ISSUE THREAD

**Issue by bmcfluff** [ucsd-progsys/liquidhaskell#525]
ResolveB.A$35$rlx is neither an argument nor a global constant in this generated qualifier:

qualif Auto(v$35$0 : ResolveB.Bar): (v$35$0 != ResolveB.A$35$rlx) // "tests/pos/Resolve.hs" (line 8, column 1)

We no longer support this, so this test is now considered broken.

**Comment by nikivazou** [comment]
Well `A` is a literal that appears in predicate definition rather than directly in the type signatures. 
We should looks at the aliases too for literals.

**Comment by ranjitjhala** [comment]
it should suffice to look at the type signature (inside which the alias is
expanded)?

On Fri, Dec 4, 2015 at 11:18 AM, Niki Vazou <notifications@github.com>
wrote:

> Well A is a literal that appears in predicate definition rather than
> directly in the type signatures.
> We should looks at the aliases too for literals.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/525#issuecomment-162057718>
> .
>



-- 
Ranjit.

**Comment by nikivazou** [comment]
I suspect it should. @bmcfluff can you try inlining the predicate and check it the problem is solved?

```
{-@ predicate NotA V = V != RB.A @-}
```

**Comment by bmcfluff** [comment]
As in just add that line to the test? That does not solve the problem.

**Comment by nikivazou** [comment]
No, replace

{-@ x :: {v:RB.Bar | ((v = RB.B) && (NotA v))} @-}


with

{-@ x :: {v:RB.Bar | ((v = RB.B) && ( v != RB.A))} @-}




On Fri, Dec 4, 2015 at 11:32 AM, bmcfluff <notifications@github.com> wrote:

> As in just add that line to the test? That does not solve the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucsd-progsys/liquidhaskell/issues/525#issuecomment-162061068>
> .
>



-- 
Niki Vazou

**Comment by bmcfluff** [comment]
Doesn't solve it.

**Comment by ranjitjhala** [comment]
I think that's what Ben already did. The qualifier generation happens after alias expansion I think?

**Comment by ranjitjhala** [comment]
Should be fixed by 6f4eb3e11f07e5d1021a5eafd3d794380630eb65

(Could cause an increase in performance as more `constant`s are tossed into `FInfo` but optimizing
those should probably happen in FP.
